### ISSUE TITLE
论文准确率问题

### ISSUE THREAD

**Issue by henrysun1996** [FlyingRoastDuck/MetaCam_DSCE#1]
请问您文论里面的MAP是几块GPU跑出来的？我试验的时候用了4块GPU，准确率跟您的有出入

**Comment by FlyingRoastDuck** [comment]
Hi，我们用的两块卡去实验的，所有结果也都是两卡去跑的。你具体说的是哪个实验结果有出入呢？无监督的还是uda的？在哪个数据集上的实验？

**Comment by henrysun1996** [comment]
好的 那我就知道啦。您这个epoch40是最优结果了吗？如果我迭代100轮会不会有更好的结果呢？还有batchsize是否需要更高呢？

**Comment by FlyingRoastDuck** [comment]
没有去尝试过使用更大的epoch和其他的batchsize，主要是观察到40epoch左右结果就基本稳定了所以就没有再去调参。batchsize=64基本算是duke和market这两个数据集的标配吧，很多工作的batchsize一般都取64或者128。另外感觉使用更多gpu并不会影响测试结果，可能是影响到模型训练的时候。一般使用更多gpu的话你需要相应地去改变学习率。

**Comment by henrysun1996** [comment]
哦哦 谢谢您。我在调参尝试尝试吧 看能不能有更好的结果。前面6个消融实验我已经跑完了，目前迁移到uda的模型在复现的时候会报错，错误是No checkpoint found at './MMTD2M.pth'  这个是需要自我下载的预训练模型吗？

**Comment by FlyingRoastDuck** [comment]
是的这个模型我已经在readme里面提供了你可以下载

**Comment by henrysun1996** [comment]
好的。已经下载好MMTD2M.pth  。
另外，您在reame文件最后提到的
![image](https://user-images.githubusercontent.com/73630873/120194396-217dd900-c250-11eb-9e02-7776d8d8cbe5.png)
这是用来做什么的啊？

**Comment by henrysun1996** [comment]
我知道了，是不是用来可视化 有无metacam的10个行人样本图的比较结果的啊？

**Comment by FlyingRoastDuck** [comment]
嗯

**Comment by henrysun1996** [comment]
知道啦 谢谢您老师

**Comment by Alex20172023** [comment]
作者你好！借助你的源码，我用一张Titan XP在market1501数据集跑“no meta，no robust loss ，with outlier”时，结果和您论文里(mAP=51.2 rank-1=73.2)的有所出入，我的结果是mAP=35.5 , rank-1=62.9。没有改动过你的任何参数，不知道哪里出错了。希望您能帮助一下我！谢谢
