### ISSUE TITLE
tabular data/ noisy instances/ new datasets

### ISSUE THREAD

**Issue by nazaretl** [FlyingRoastDuck/MetaCam_DSCE#3]
Hi,
thanks for sharing your implementation. Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by FlyingRoastDuck** [comment]
Please refer to the following code:

https://github.com/FlyingRoastDuck/MetaCam_DSCE/blob/master/train_usl_no_outlier.py#L136
