### ISSUE TITLE
论文补充材料

### ISSUE THREAD

**Issue by blessingyr** [FlyingRoastDuck/MetaCam_DSCE#4]
您好，想问一下论文的补充材料在哪里下载呢？

**Comment by FlyingRoastDuck** [comment]
你好，请去CVF Open access下载：
https://openaccess.thecvf.com/content/CVPR2021/supplemental/Yang_Joint_Noise-Tolerant_Learning_CVPR_2021_supplemental.pdf

另外， 我们arxiv版本已经把supp融进去了
